//
//  IssueListWireframe.swift
//  MyGitLab
//
//  Created by PHAM ANH TUAN on 11/06/2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit
import RxSwift
import RxCocoa

final class IssueListWireframe: BaseWireframe {

    // MARK: - Private properties -

    private let storyboard = UIStoryboard(name: "IssueList", bundle: nil)

    // MARK: - Module setup -

    init() {
        let moduleViewController = storyboard.instantiateViewController(ofType: IssueListViewController.self)
        super.init(viewController: moduleViewController)

        let interactor = IssueListInteractor()
        let presenter = IssueListPresenter(view: moduleViewController, interactor: interactor, wireframe: self)
        moduleViewController.presenter = presenter
    }

}

// MARK: - Extensions -

extension IssueListWireframe: IssueListWireframeInterface {
    func navigate(to option: IssueListNavigationOption) {
        switch option {
        case .issueDetail(let issue):
            let wireframe = IssueDetailWireframe(issue: issue)
            navigationController?.pushWireframe(wireframe)
        }
    }
}
