//
//  IssueListInteractor.swift
//  MyGitLab
//
//  Created by PHAM ANH TUAN on 11/06/2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation
import RxSwift
import Resolver

protocol IssueListInteractorInterface: InteractorInterface {
    func fetchIssues(of gitlabRepository: String,  after: String) -> Observable<MGLIssuePagination>
}

final class IssueListInteractor {
    @LazyInjected var myGitLabService: MyGitLabServiceType
}

// MARK: - Extensions -

extension IssueListInteractor: IssueListInteractorInterface {
    func fetchIssues(of gitlabRepository: String, after: String) -> Observable<MGLIssuePagination> {
        return myGitLabService.fetchIssues(of: gitlabRepository, first: 10, after: after)
    }
}
