//
//  MainViewController.swift
//  MyGitLab
//
//  Created by PHAM ANH TUAN on 11/06/2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit
import RxSwift
import RxCocoa

final class MainViewController: UIViewController {

    // MARK: - Public properties -

    var presenter: MainPresenterInterface!

    // MARK: - Private properties -

    private let disposeBag = DisposeBag()

    // MARK: - Lifecycle -

    override func viewDidLoad() {
        super.viewDidLoad()
        setupView()
    }

}

// MARK: - Extensions -

extension MainViewController: MainViewInterface {
}

private extension MainViewController {

    func setupView() {
        let output = Main.ViewOutput()

        let input = presenter.configure(with: output)
    }

}
