//
//  MainInteractor.swift
//  MyGitLab
//
//  Created by PHAM ANH TUAN on 11/06/2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation
import RxSwift

final class MainInteractor {
}

// MARK: - Extensions -

extension MainInteractor: MainInteractorInterface {
}
