//
//  MainInterfaces.swift
//  MyGitLab
//
//  Created by PHAM ANH TUAN on 11/06/2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit
import RxSwift
import RxCocoa

protocol MainWireframeInterface: WireframeInterface {
}

protocol MainViewInterface: ViewInterface {
}

protocol MainPresenterInterface: PresenterInterface {
    func configure(with output: Main.ViewOutput) -> Main.ViewInput
}

protocol MainInteractorInterface: InteractorInterface {
}

enum Main {

    struct ViewOutput {
    }

    struct ViewInput {
    }

}
