//
//  IssueDetailInteractor.swift
//  MyGitLab
//
//  Created by PHAM ANH TUAN on 11/06/2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation
import RxSwift
import Resolver

protocol IssueDetailInteractorInterface: InteractorInterface {
    func fetchDiscussions(after: String) -> Observable<MGLIssueDiscussionsPagination>
}

final class IssueDetailInteractor {
    
    @LazyInjected private var myGitlabService: MyGitLabServiceType
    let issueId: String
    
    init(issueId: String) {
        self.issueId = issueId
    }
}

// MARK: - Extensions -

extension IssueDetailInteractor: IssueDetailInteractorInterface {
    func fetchDiscussions(after: String) -> Observable<MGLIssueDiscussionsPagination> {
        return myGitlabService.fetchDiscussions(of: "gnachman/iterm2", for: issueId, first: 10, after: after)
    }
}
