//
//  IssueDetailWireframe.swift
//  MyGitLab
//
//  Created by PHAM ANH TUAN on 11/06/2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit
import RxSwift
import RxCocoa

final class IssueDetailWireframe: BaseWireframe {

    // MARK: - Private properties -

    private let storyboard = UIStoryboard(name: "IssueDetail", bundle: nil)

    // MARK: - Module setup -

    init(issue: MGLIssue) {
        let moduleViewController = storyboard.instantiateViewController(ofType: IssueDetailViewController.self)
        super.init(viewController: moduleViewController)

        let interactor = IssueDetailInteractor(issueId: issue.iid)
        
        let presenter = IssueDetailPresenter(
            view: moduleViewController,
            interactor: interactor,
            wireframe: self,
            issue: issue
        )
        
        moduleViewController.presenter = presenter
    }

}

// MARK: - Extensions -

extension IssueDetailWireframe: IssueDetailWireframeInterface {
}
